import { FileDown, FileSpreadsheet, Printer } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { toast } from '@/components/ui/Toast';

interface Column {
  key: string;
  label: string;
}

interface ReportExportProps {
  data: Record<string, unknown>[];
  columns: Column[];
  title: string;
  filename: string;
}

export function ReportExport({ data, columns, title, filename }: ReportExportProps) {
  const exportCSV = () => {
    const header = columns.map((c) => c.label).join(',');
    const rows = data.map((row) =>
      columns.map((c) => {
        const val = String(row[c.key] ?? '');
        return val.includes(',') ? `"${val}"` : val;
      }).join(',')
    );
    const csv = [header, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.csv`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success(`Exported ${data.length} rows as ${filename}.csv`, 'Excel Export');
  };

  const exportPDF = () => {
    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) return;

    const tableRows = data.map((row) =>
      `<tr>${columns.map((c) => `<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#374151;">${row[c.key] ?? ''}</td>`).join('')}</tr>`
    ).join('');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title} — Stryde Health</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 40px; color: #111827; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #0D9488; }
          .brand { font-size: 22px; font-weight: 700; color: #0D9488; }
          .subtitle { font-size: 12px; color: #6b7280; margin-top: 4px; }
          .title { font-size: 18px; font-weight: 600; color: #111827; text-align: right; }
          .date { font-size: 11px; color: #9ca3af; text-align: right; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; }
          th { padding: 10px 12px; text-align: left; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; background: #f9fafb; border-bottom: 2px solid #e5e7eb; }
          .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">Stryde Health</div>
            <div class="subtitle">Hospital Information System</div>
          </div>
          <div>
            <div class="title">${title}</div>
            <div class="date">Generated: ${new Date().toLocaleString()}</div>
          </div>
        </div>
        <table>
          <thead><tr>${columns.map((c) => `<th>${c.label}</th>`).join('')}</tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
        <div class="footer">This report was generated by Stryde Health HIS. Data shown is for the selected period only.</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    toast.success('PDF report generated and sent to print dialog.', 'PDF Export');
  };

  const handlePrint = () => {
    window.print();
    toast.info('Print dialog opened.', 'Print');
  };

  return (
    <div className="flex items-center gap-2">
      <Button variant="secondary" size="sm" onClick={exportPDF}>
        <FileDown className="w-4 h-4" />
        Export PDF
      </Button>
      <Button variant="secondary" size="sm" onClick={exportCSV}>
        <FileSpreadsheet className="w-4 h-4" />
        Export Excel
      </Button>
      <Button variant="ghost" size="sm" onClick={handlePrint}>
        <Printer className="w-4 h-4" />
        Print
      </Button>
    </div>
  );
}
